### ISSUE TITLE
EventOperation Enum

### ISSUE THREAD

**Issue by altmank** [TomMalow/ExtendedPlugin.cs#1]
Hey, I'm looking into using this plugin base class and have a question about the EventOperation enum. 

It looks like it only implements a subset of the available "EventOperations" or messages available to D365. E.g. it does not implement "Merge", "AddMember", "AddToQueue", and so on. 

What is the reason for this? Is the intention for additional messages to be added to the enum as needed? 

Also, I noticed the EventOperations enum numbering appears to be a sequence that would typically  be used for a bit flag but I didn't see any implementation supporting that. Was there some other intent behind that?

**Comment by TomMalow** [comment]
I believe you are looking at an old version of the file. [The "latest" version for Daxif v2.2.07 and up](https://github.com/TomMalow/ExtendedPlugin.cs/blob/master/v2.2.0.7%2B/Plugin.cs), should contain the messages that you mentioned. Do note that this version was created 4 years ago and there might be some new event operations that does not exist in the list. The intention is to update it as needed.

Additionally, the enum numbering have been changed to be default instead of using bit sequence. I believe it was made that way by the original creator. He had a thing for numbering enums that way.

I might move this file over to Delegate A/S repo instead. Makes sense to keep it together.

**Comment by altmank** [comment]
Ahh, that makes sense. Thanks for clarifying.
